version: "3.9"
services:
  rotator:
    build: .
    restart: always


    # -- FILL THIS OUT ---

    volumes:
      - "/path/to/images/:/dppr/data/"
      # pick a directory that will contain all of your images. Replace "/path/to/images/" with that path.
    environment:
      TOKEN: "<PLACE YOUR TOKEN HERE>"
      # if you are having problems, make sure your token is correct, then redeploy this docker compose file
      INTERVAL: "900" # the time interval that your profile picture should be changed. This number is in SECONDS.
      # make sure this is higher than 10 minutes as Discord has an Avatar change rate limit.